
[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Light Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Light"

[window]
opacity = 0.99
blur = true

[general]
import = ["/home/vp/.alacritty-colorscheme/themes/one_dark.toml"]

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"

[[keyboard.bindings]]
key = "Tab"
mods = "Control"
chars = "\u001b[1;5C"

[[keyboard.bindings]]
key = "Tab"
mods = "Control|Shift"
chars = "\u001b[1;5D"

